### ISSUE TITLE
InvalidResponseException when starting farm mode.

### ISSUE THREAD

**Issue by darkhax** [Novalys/PokemonGo-Bot-SimpleGUI#151]
The following exception is thrown when clicking on the start farming option. Happens every now and then, especially if the bot has been left idle for a few minutes. 
```
************** Exception Text **************
PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Novalys\Desktop\PokemonGo-Bot-SimpleGUI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Novalys\Desktop\PokemonGo-Bot-SimpleGUI\PokemonGo.RocketAPI\Client.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPokemons>d__11.MoveNext() in C:\Users\Novalys\Desktop\PokemonGo-Bot-SimpleGUI\PokemonGo.RocketAPI.Logic\Inventory.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<PreflightCheck>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<startToolStripMenuItem_Click>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by SamuriBakePie** [comment]
Niantic updated their api today, gotta wait on the owner to get on to fix it

**Comment by SamuriBakePie** [comment]
Come into discord, theres a temp fix

**Comment by tazzcom** [comment]
Please do tell about this temp fix ^.^

**Comment by dtmcode** [comment]
Temp fix by Mulch here: https://github.com/dtmcode/PokemonGo-Bot-SimpleGUI

**Comment by tazzcom** [comment]
sorry but not even sure what to do with that fix...lol. I'm the simple exe user. =D

**Comment by dtmcode** [comment]
This is the .exe Mulch posted on discord @tazzcom 

https://www.sendspace.com/file/nqn92m

**Comment by tazzcom** [comment]
Nice, thanks for the link, working perfectly.  Sorry for my basicness :)

**Comment by nxy** [comment]
PokemonGo.RocketAPI.GUI\MainForm.cs
   
        private async Task ExecuteFarmingPokestopsAndPokemons()
        {
            var mapObjects = await _client.GetMapObjects();

            var pokeStops = mapObjects.MapCells.SelectMany(i => i.Forts).Where(i => i.Type == FortType.Checkpoint && i.CooldownCompleteTimestampMs < DateTime.UtcNow.ToUnixTime());

            var fortDatas = pokeStops as IList<FortData> ?? pokeStops.ToList();
            _pokestopsCount = fortDatas.Count<FortData>();
            int count = 1;

            foreach (var pokeStop in fortDatas)
            {
                var update = await _client.UpdatePlayerLocation(pokeStop.Latitude, pokeStop.Longitude, _settings.DefaultAltitude); // Redundant?
                UpdateMap(pokeStop.Latitude, pokeStop.Longitude);
                var fortInfo = await _client.GetFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);

                boxPokestopName.Text = fortInfo.Name;
                boxPokestopInit.Text = count.ToString();
                boxPokestopCount.Text = _pokestopsCount.ToString();
                count++;                               

				await Task.Delay(2000);
                var fortSearch = await _client.SearchFort(pokeStop.Id, pokeStop.Latitude, pokeStop.Longitude);
                Logger.Write($"Loot -> Gems: { fortSearch.GemsAwarded}, Eggs: {fortSearch.PokemonDataEgg} Items: {StringUtils.GetSummedFriendlyNameOfItemAwardList(fortSearch.ItemsAwarded)}");
                Logger.Write("Gained " + fortSearch.ExperienceAwarded + " XP.");

                // Experience Counter
                _totalExperience += fortSearch.ExperienceAwarded;

                await GetCurrentPlayerInformation();
                Logger.Write("Attempting to Capture Nearby Pokemons.");
				await Task.Delay(2000);
                await ExecuteCatchAllNearbyPokemons();

                if (!_isFarmingActive)
                {
                    Logger.Write("Stopping Farming Pokestops.");
                    return;
                }                    

                Logger.Write("Waiting before moving to the next Pokestop.");
                await Task.Delay(GUISettings.Default.pokestopDelay * 1000);
            }}

**Comment by Dbarr74** [comment]
I updated it, both with the file and updating the mainform, but it keeps doing the attempting to retrieve inventory and player profile loop with the google token.

**Comment by yupdon** [comment]
Hey i added a task.wait() in some places, err free hotfix if interested, #157

**Comment by nxy** [comment]
#164

**Comment by nxy** [comment]
#164
