### ISSUE TITLE
The designer could not be shown for this file because none of the classes within it can be designed.    

### ISSUE THREAD

**Issue by GodSpeed2323** [Novalys/PokemonGo-Bot-SimpleGUI#173]
https://gyazo.com/c8bc3222fdfa2b1c0e9706213b148adb

The designer could not be shown for this file because none of the classes within it can be designed.    
 
  
 
     
Instances of this error (1)  
 
1.   Show Call Stack  
 
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.EnsureDocument(IDesignerSerializationManager manager)
at System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.DeferredLoadHandler.Microsoft.VisualStudio.TextManager.Interop.IVsTextBufferDataEvents.OnLoadCompleted(Int32 fReload)  
   
Help with this error  
 
MSDN Help   
 
   
Forum posts about this error  
 
Search the MSDN Forums for posts related to this error

**Comment by GodSpeed2323** [comment]
tried with both vs 2013 and 2015

**Comment by WooAf** [comment]
Rebuild
