### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Dyndrilliac** [Novalys/PokemonGo-Bot-SimpleGUI#201]
I updated to 1.4, started a farming run, and left it unattended. When I came back, I saw the above error message in the console and the message box that pops up when I stop the bot (asking me to wait until all pending tasks had been completed) was displayed on the screen. I closed it, then tried to open my pokemon list, and an unhandled PokemonGo.RocketAPI.Exceptions.InvalidResponseException was thrown.

Just before the error occurred, it had encountered three pokemon (all of which were successfully caught) and was waiting for the delay to end before engaging a fourth. This was also at the first pokestop after a complete lap around the area and automatically transferring/evolving the pokemon in my inventory. Total run time before hitting the error was 1611 seconds. Logs are attached below.

[log.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/393336/log.txt)
[Farming.ErrorLog.20160801044615235.txt](https://github.com/Novalys/PokemonGo-Bot-SimpleGUI/files/393346/Farming.ErrorLog.20160801044615235.txt)

**Comment by ryandailey100** [comment]
I am having the same problem too. I suspect it happens once the player has reached the max pokemon cap while farming.

**Comment by LitoOsaka** [comment]
Same problem here. So far the most stable version for me yet is 1.2.

**Comment by chromeplatedhrt** [comment]
Having the same issue as well. Have restarted in the same location 3 times and I get the error after different periods of time, but before I reach all stops.

**Comment by OTTORE** [comment]
I get this aswell, I haven't tested yet but could this be from an egg hatching? Or does the system handle that fine?

**Comment by Dyndrilliac** [comment]
@ryandailey100  I don't think so, I wasn't anywhere near the cap when the issue occurred.

@OTTORE Not unless a recent change has broken the behavior. I've had eggs hatch while farming with v1.2 without issues. I've also gotten eggs from pokestops without issues.

**Comment by NoFootprintsGG** [comment]
The error always occures in the same situation for me, just like this:

[03:57:20] Attempting to Capture Nearby Pokemons.
[03:57:22] Found 2 Pokemons in the area.
[03:57:25] Error: Object reference not set to an instance of an object.
...
[04:12:47] Attempting to Capture Nearby Pokemons.
[04:12:48] Found 1 Pokemons in the area.
[04:12:50] Error: Object reference not set to an instance of an object.

Directly after finding a Pokemon it crashes.
Maybe it's a certain Pokemon that causes the problem, no idea how exactly though.
It's definitely unrelated to how many stops have been visited or how many Pokemon have been caught before imo.

**Comment by cvbkf** [comment]
Same problem here, here the log from farmingerror.xxxx

Object reference not set to an instance of an object.

   at PokemonGo.RocketAPI.Logic.Logic.CalculatePokemonPerfection(PokemonData poke) in C:\projects\pokemongo-bot-simplegui\PokemonGo.RocketAPI.Logic\Logic.cs:Zeile 37.
   at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteCatchAllNearbyPokemons>d__52.MoveNext()
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.GUI.Navigation.HumanWalking.<Walk>d__5.MoveNext()
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__51.MoveNext()
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<StartBottingSession>d__35.MoveNext()

**Comment by Markmanus** [comment]
I have got the same error, i can copy the windows log file if necessary , unfortunately i couldn't copy the log from the app.

**Comment by Novalys** [comment]
This should be fixed now with the latest version 1.5, please try and let me know.
