### ISSUE TITLE
Problem with Snipe Pokemon

### ISSUE THREAD

**Issue by cucurettu** [Novalys/PokemonGo-Bot-SimpleGUI#228]
I know that the Snipe Pokeman is in Beta version, but I have a problem that doesn't allow me to use it.
Briefly, I put the coordinates from http://spawns.sebastienvercammen.be/ in the provided space and I click "start". In the console appears that the coordinates are valid, but after 1 seconds a new window appears with these words "Error during Pokemon Snipe, see details in results box". These are the results in the box:

System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Nome parametro: Latitude
   in GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:riga 109
   in PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by A-VORONKIN** [comment]
I hade always https://gyazo.com/d0cf0999bfabf3e36ca28aa1bb9d1e38

System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext() in C:\Users\Andriy\Documents\Visual Studio 2015\Projects\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI.GUI\PokemonSnipingForm.cs:line 52

**Comment by orakles** [comment]
System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by Botic0** [comment]
Working great for me snip multiple pokemon i wanted first time ever using a bot loving it :) i how ever did get this error once or twice i just restarted :)

**Comment by NoFootprintsGG** [comment]
For me the exact same thing is happening as for @cucurettu

**Comment by cucurettu** [comment]
@A-VORONKIN I have to change this "." of the coordinates into a ","

**Comment by OTTORE** [comment]
Does using this system put the account at risk for a ban if the location is no where near the current location?

**Comment by NoFootprintsGG** [comment]
@cucurettu Why would he need to do that? http://spawns.sebastienvercammen.be/ provides the coordinates the right way and they are written exactly as the example demands.

@OTTORE Nothing happened thus far except softbans which this bot can remove aswell. Same risk as with every other tool.

**Comment by OTTORE** [comment]
@NoFootprintsGG alright cool, I suppose I can unfamiliar with the system behind softbans (3 strikes youre out?) so I didnt know if it was very unsafe or not.

**Comment by A-Charvin** [comment]
More like 20 Strikes. As of now there are only reports about IP ban's around the corner and no perma bans so it's safe.

**Comment by cucurettu** [comment]
Someone can explain me what I have to do to use Poke Snipe? Maybe I make a mistake somewhere

**Comment by A-Charvin** [comment]
![capture](https://cloud.githubusercontent.com/assets/20741723/17327397/536031d2-58d5-11e6-9a53-35ecc30f5a31.PNG)

The steps are all right there.

**Comment by cucurettu** [comment]
@A-Charvin In this case I can tell you that the error is the same wich all the coordinates that i put in that box;
System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Nome parametro: Latitude
   in GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:riga 109
   in PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by cucurettu** [comment]
Only if i put in the coordinates "90, -90" it tell me this:
Coordinates are valid.
Teleported to Snipe Location.
Will try to remove soft ban now, this will take less than 1 minute.
No Pokestops Found in the Area, won't be able to remove soft ban.
Unable to remove soft ban, most likely the Pokemon(s) will run away.
Walking from Pokestop to the Pokemon, will take 0,0 seconds...
Arrived to Pokemon Location, will try to catch it now.
No Pokemon(s) found in the area.
Sniping Complete.

**Comment by eXplosio** [comment]
System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Nome parametro: Latitude
   in GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:riga 109
   in PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

I write this cordinate in this way: 33.991316, -118.470383

**Comment by cucurettu** [comment]
@eXplosio same problem

**Comment by ikki03** [comment]
When i try i see that the right format was : 118,470383, -33,991316 

But i style have the same problem that @cucurettu @eXplosio but with -180 180

**Comment by ikki03** [comment]
-33,857117784123, 151,215116362756
i obtained the error -180 180

151,215116362756, -33,857117784123
i obtained the error -90 90

but when i tried 80, -33,857117784123 it works but it's not accurate coordonates

**Comment by eXplosio** [comment]
Where did you get that ' 80 ?

**Comment by eXplosio** [comment]
Din't work for me

**Comment by cucurettu** [comment]
80, -33,857117784123 work for me, but as he saied this are two random numbers. I think they work because they are between -90 and 90. But I don't know why other people are able to put other coordinates and the Poke Sniper work.

**Comment by A-Charvin** [comment]
It may be due to some conversion issues in the code.
I'm not sure, since i don't know much about the same.
```

// Verify the Coordinates are valid
                string[] coordinates = boxCoordinates.Text.Trim().Split(',');
                double lat = double.Parse(coordinates[0]);
                double lng = double.Parse(coordinates[1]);
                textResults.AppendText("Coordinates are valid." + Environment.NewLine);

```

**Comment by eXplosio** [comment]
80, -33,857117784123 These cordinates are also fine to me even though I did not find anything, but I do not know what number to add to the other ...

**Comment by cucurettu** [comment]
@A-Charvin everytime I put coordinates in the box appear that coordinates are valid, but after this it say that is an error and the coordinates must be between -90 and 90, and sometimes between -180 and 180.
For exmaple, this are working coordinates of Vaporeon 42.80987, -1.600404, but they don't work for me because it say that coordinates must be between -90 and 90. So I have changed them in 42, -1.600404, and the error has changed in "must be between -180 and 180".

**Comment by eXplosio** [comment]
yea same problem

**Comment by reapo** [comment]
Adding this at the beginning of the code:
`using System.Thread;
`
and this before double.Parse([...]);
```
string delim = Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator;
coordinates[0].Replace(".", delim);
coordinates[1].Replace(".", delim);
```
should fix it.

This will change the "." delimiter for decimals to whatever the locale is for the user (which could be "." or ",");

**Comment by cucurettu** [comment]
@reapo wait, in which file?

**Comment by Sbrown-WilliamsCrusher** [comment]
@cucurettu in the PokemonSnipingForm.cs

**Comment by dosenhosenjoe** [comment]
@reapo can you show how the whole part of the code looks like after it ?

**Comment by cucurettu** [comment]
@Sbrown-WilliamsCrusher I'm sorry but I'm not a genius with this things. I have downloaded the bot archive 1.5, but there isn't a file called PokemonSnipingForm.cs

**Comment by dosenhosenjoe** [comment]
@cucurettu you need to download the code and open with visual studio 2015

**Comment by waldof123** [comment]
For me the issue was caused due to the regional settings of pc.
I changed the Decimal symbol to . and list separator to ,
Hope it will help someone as well.

**Comment by reapo** [comment]
@dosenhosenjoe 

PokemonSnipingForm.cs: Line 51:

Before:
```
// Verify the Coordinates are valid
string[] coordinates = boxCoordinates.Text.Trim().Split(',');
double lat = double.Parse(coordinates[0]);
double lng = double.Parse(coordinates[1]);
```

After
```
// Verify the Coordinates are valid
string[] coordinates = boxCoordinates.Text.Trim().Split(',');
string delim = Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator;
coordinates[0].Replace(".", delim);
coordinates[1].Replace(".", delim);
double lat = double.Parse(coordinates[0]);
double lng = double.Parse(coordinates[1]);
```

**Comment by dosenhosenjoe** [comment]
@reapo i put it in just like that and it still didnt work

**Comment by lotzxd** [comment]
After that i change the code, how can I run de program?

**Comment by Novalys** [comment]
It's an amazing feeling waking up and seeing people working towards fixing something, just tried to catch a Pikachu.

![image](https://cloud.githubusercontent.com/assets/368854/17335327/cd752f66-5896-11e6-9e12-7cebc98f40cf.png)

**Comment by Novalys** [comment]
@cucurettu you should be able to download it from the [latest source build](https://ci.appveyor.com/api/projects/Novalys/pokemongo-bot-simplegui/artifacts/PoGo-Bot_SimpleGUI-Latest.zip), this is an automated service that builds the latest code and creates a binary (exe) it's not the most stable version but it has the latest features including this fix.

**Comment by cucurettu** [comment]
@Novalys I have downloaded it just 10 minutes ago and I have corrected the code as Reapo saied. Now how can I run the program with this new code file?

**Comment by Sbrown-WilliamsCrusher** [comment]
@cucurettu the latest source build has the fix included no need to edit code

**Comment by cucurettu** [comment]
Ok now it work and I hope it work for all the people that had my same problem. Thank you!

**Comment by Sbrown-WilliamsCrusher** [comment]
Cool! Pending Close then

**Comment by Novalys** [comment]
<Closes this while doing a happy dance> :smile:
