### ISSUE TITLE
Snipe Error

### ISSUE THREAD

**Issue by derohimat** [Novalys/PokemonGo-Bot-SimpleGUI#237]
System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by iKonatai** [comment]
PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Novalys\Projects\PokemonGo-Bot-SimpleGUI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<UpdatePlayerLocation>d__43.MoveNext() in C:\Users\Novalys\Projects\PokemonGo-Bot-SimpleGUI\PokemonGo.RocketAPI\Client.cs:line 404
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.GUI.Navigation.HumanWalking.<Walk>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

I get this error ^

**Comment by Smallsucks** [comment]
System.ArgumentOutOfRangeException: Argument must be in range of -90 to 90
Parameter name: Latitude
   at GeoCoordinatePortable.GeoCoordinate.set_Latitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 109
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by kjellar** [comment]
This is the error I get, some of it gets translated to my language, so I'll translate it back.

System.FormatException: Internal data string had invalid format.
   by System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   by PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by Sbrown-WilliamsCrusher** [comment]
This error should be fixed in the Unstable release: https://ci.appveyor.com/api/projects/Novalys/pokemongo-bot-simplegui/artifacts/PoGo-Bot_SimpleGUI-Latest.zip
If you are using the stable release please wait for 1.6 or use the unstable release
Reference PR #235 and Issue #228 
If the unstable does not fix please let me know.
