### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by filipinousmc** [Novalys/PokemonGo-Bot-SimpleGUI#238]
System.ArgumentOutOfRangeException: Argument must be in range of -180 to 180
Parameter name: Longitude
   at GeoCoordinatePortable.GeoCoordinate.set_Longitude(Double value) in C:\projects\geocoordinate\src\GeoCoordinatePortable\GeoCoordinate.cs:line 129
   at PokemonGo.RocketAPI.GUI.Helpers.LocationUtils.CalculateDistanceInMeters(Double sourceLat, Double sourceLng, Double destLat, Double destLng)
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<ForceUnban>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()

**Comment by cucurettu** [comment]
Have you tried to change coordinates? It happened to me too this error, but simply I changed coordinates with others of another pokemon and the error didn't appeared

**Comment by filipinousmc** [comment]
It happen couple times in a row. So i force shutdown and rebooted the
program.

Victor Levy
Cell: 910-381-8405
email: victorlevyusmc@gmail.com

**Comment by Sbrown-WilliamsCrusher** [comment]
Duplicate of #237
