### ISSUE TITLE
Pokemon Snipe problem

### ISSUE THREAD

**Issue by xXBenlitoXx** [Novalys/PokemonGo-Bot-SimpleGUI#240]
When I try do snipe a pokemon I always get this Error message "Error during Pokemon Snipe, see details in results box." and this is what I get System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()
  How can I fixes this!!!

**Comment by Sbrown-WilliamsCrusher** [comment]
Duplicate #237

**Comment by xXBenlitoXx** [comment]
How can I fix this?

**Comment by Sbrown-WilliamsCrusher** [comment]
Close this issue and look at issue #237

**Comment by xXBenlitoXx** [comment]
Okey thanks

**Comment by filipinousmc** [comment]
If you keep using Poke Snipe then I suggest deleting the entire file from your computer and then reinstalling the file back on. Its only temporary considering that after puttiing in the coordinates about 4 or 5 times that error will come back again. Hopefully V6 will fix the issue.

**Comment by xXBenlitoXx** [comment]
I intalled it today at I saw the feature Pokemon Snipe and I tryed using
but dosen't want to work I always get tha error than I tryed deleting the
file and install it again and it happend again.

**Comment by filipinousmc** [comment]
Did you completely delete it. Including the recycle bin.

Victor Levy
Cell: 910-381-8405
email: victorlevyusmc@gmail.com

**Comment by xXBenlitoXx** [comment]
Yes

**Comment by filipinousmc** [comment]
Including the download folder? Then reinstall from the git page?

Victor Levy
Cell: 910-381-8405
email: victorlevyusmc@gmail.com

**Comment by Sbrown-WilliamsCrusher** [comment]
Okay which version of the bot are you using the Latest build (v1.5) or the latest source build?

**Comment by xXBenlitoXx** [comment]
Version 1.5

**Comment by Sbrown-WilliamsCrusher** [comment]
OKay Please install the latest source build from https://github.com/Novalys/PokemonGo-Bot-SimpleGUI#the-simple and let me know if the problem persists

**Comment by BrecasPT** [comment]
I was trying to snipe a Gyarados and when the bot arrived on his location after unbaning me and walking to the location appeared saying that 2 Pokemons where find in the area and then it crashed
(Using unstable version)



System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<ExecuteCatchAllNearbyPokemons>d__9.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   em PokemonGo.RocketAPI.GUI.PokemonSnipingForm.<btnSnipe_Click>d__6.MoveNext()
