### ISSUE TITLE
Message: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.

### ISSUE THREAD

**Issue by pacinoallstars** [Novalys/PokemonGo-Bot-SimpleGUI#38]
After some time (between 30 minutes and 60 minutes the bot will crash and wont restart. 

Message: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
StackTrace:    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<GetMapObjects>d__32.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Client.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<startBottingSession>d__29.MoveNext()

**Comment by alecstheone** [comment]
I get this error too

**Comment by Novalys** [comment]
Yes this is a major bug, we are tracking this in Issue #42 , I'll close this one to avoid duplicates and keep the conversation in the other issue.
