### ISSUE TITLE
Bot Crashes after Extended Usage (5 Second Spam Crash)

### ISSUE THREAD

**Issue by mich3lam** [Novalys/PokemonGo-Bot-SimpleGUI#42]
it keeps crashing, spamming the msg and crashlog.txt files in directory

**Comment by UncleMart** [comment]
Do me a favour and look at the log.txt file and go to the end. you'll see lots of 

> [14:46:35] Bot Crashed! :( Starting again in 5 seconds...

> 
In between each of these should be another line, could you paste what it says there?

I've had a few crashes and found it will say this : 

> [14:46:35] Bot Crashed! :( Starting again in 5 seconds...
[14:46:40] Requesting GetMapObjectsResponse

> 

So it looks like the GetMapObjectsResponse function is having problems for me, just wondering if it's the common error people are getting.

**Comment by Tombraider** [comment]
i get it aswell i can restart it over every 20 minuts or so

**Comment by UncleMart** [comment]
Thanks for checking that for me bud :) hopefully the dev will be able to track this down a little easier now :) But yeah, I'm having to restart it periodically too, it sucks but this bot is amazing so far :)

**Comment by wygasmateusz** [comment]
Error code `Message: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
StackTrace:    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Client.cs:line 201`

**Comment by mich3lam** [comment]
I am currently testing a fix

**Comment by mich3lam** [comment]
{
                    Logger.Write("Bot Crashed! :( Starting again in 5 seconds...");
                    createCrashLog(ex);
                    System.Threading.Thread.Sleep(5000);
                }

changed to

                {
                    Logger.Write("Bot Crashed! :( Starting again in 5 seconds...");
                    createCrashLog(ex);
                    System.Threading.Thread.Sleep(5000);
                    await ExecuteFarmingPokestopsAndPokemons();
                }

bot crashed, and restarted :)

**Comment by michwesterhof** [comment]
what files / file location should we add that as temp fix?

**Comment by mich3lam** [comment]
PokemonGo-Bot-SimpleGUI/PokemonGo.RocketAPI.GUI/MainForm.cs

**Comment by Tombraider** [comment]
Message: Er is een uitzondering opgetreden van het type PokemonGo.RocketAPI.Exceptions.InvalidResponseException.
StackTrace:    bij PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:regel 39
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.Client.<GetMapObjects>d__32.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Client.cs:regel 254
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__39.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.GUI.MainForm.<startBottingSession>d__29.MoveNext()


At my computer atm and i'l just put the error here for the devs to look at

**Comment by michwesterhof** [comment]
still trows and exception when it tries to restart.

**Comment by mich3lam** [comment]
been working for me :\ i dunno

**Comment by Tombraider** [comment]
Message: De objectverwijzing is niet op een exemplaar van een object ingesteld.
StackTrace:    bij PokemonGo.RocketAPI.GUI.MainForm.<ExecuteCatchAllNearbyPokemons>d__40.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__39.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij PokemonGo.RocketAPI.GUI.MainForm.<startBottingSession>d__29.MoveNext()


And a sepperate one.

**Comment by brolifen** [comment]
Same here, crashes everytime after about 30min
Starts with a couple of these:
`Message: Object reference not set to an instance of an object.
StackTrace:    at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteCatchAllNearbyPokemons>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<startBottingSession>d__29.MoveNext()
`

And then keeps going with these:

`Message: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
StackTrace:    at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Client.<GetMapObjects>d__32.MoveNext() in C:\Users\Novalys\Projects\PoGO-SimpleGUI\PokemonGo.RocketAPI\Client.cs:line 254
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<ExecuteFarmingPokestopsAndPokemons>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<startBottingSession>d__29.MoveNext()
`

**Comment by Novalys** [comment]
This is the major bug currently on the bug I'm investigating what is causing it but it seems is something from the API/Logic. As you might now I'm not adding features to the logic, mostly converting the project to a simple GUI but I'll check into this and modify the API to solve this problem.

**Comment by michwesterhof** [comment]
i think as long as we can use the gui and bot perfectly without bugs we're all happy for your time invested ;)

**Comment by kirkwasgeht** [comment]
this happens for me aswell, is this getting fixed?

**Comment by Mineroboter** [comment]
I think sometimes the bot gets somehow an invalid response from the server and the API returns correctly a InvalidResponseException but the Logic and the GUI can't handle that there is no valid response and the bot crashes. So the bot should try to send the request again after waiting x seconds if he gets an invalid response. But he should only try that 3 times or so.
I think that's exactly the point where the app also freezes sometimes: The app also can't handle the invalid response and freezes.
But that's only my assumptions..

**Comment by mich3lam** [comment]
@Novalys can fix anything :dancers: hopefully it'll take a look at it when he comes back.. i just love this project! and @Mineroboter thank you too for the contribution to it!

**Comment by Tombraider** [comment]
In addition of this issue, i think it has to do with the full bag function, when it collects and reaches a full bag it started to get buggy, it won't delete items from the bag once its full, and that can be fairly quickly. It needs a function where it deletes items such as potions when it spins a pokestop.

**Comment by Nexoru** [comment]
I have the same issue. I hope he can fix it quick :+1:

**Comment by A-VORONKIN** [comment]
Same problem

**Comment by darkhax** [comment]
For those worried about the logs spamming your hard drive, you can run `del /q CrashLog.*` in the app directory to delete them. This can also be placed in a batch file.

**Comment by Novalys** [comment]
This should be fixed now!
