### ISSUE TITLE
Crash with log

### ISSUE THREAD

**Issue by Wyn10** [Novalys/PokemonGo-Bot-SimpleGUI#55]
Happens every once in a while.
```
************** Exception Text **************
PokemonGo.RocketAPI.Exceptions.InvalidResponseException: Exception of type 'PokemonGo.RocketAPI.Exceptions.InvalidResponseException' was thrown.
   at PokemonGo.RocketAPI.Extensions.HttpClientExtensions.<PostProtoPayload>d__1`2.MoveNext() in C:\Users\Wyn\Desktop\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI\Extensions\HttpClientExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Client.<GetInventory>d__30.MoveNext() in C:\Users\Wyn\Desktop\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI\Client.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetPokemons>d__11.MoveNext() in C:\Users\Wyn\Desktop\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI.Logic\Inventory.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PokemonGo.RocketAPI.Logic.Inventory.<GetDuplicatePokemonToTransfer>d__2.MoveNext() in C:\Users\Wyn\Desktop\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI.Logic\Inventory.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<TransferDuplicatePokemon>d__35.MoveNext() in C:\Users\Wyn\Desktop\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI.GUI\MainForm.cs:line 591
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.GUI.MainForm.<btnTransferDuplicates_Click>d__18.MoveNext() in C:\Users\Wyn\Desktop\PokemonGo-Bot-SimpleGUI-master\PokemonGo.RocketAPI.GUI\MainForm.cs:line 321
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by Novalys** [comment]
Yes this is already reported and being worked on Issue #42 Thanks for the report!

**Comment by Wyn10** [comment]
@Novalys Sorry, didn't see..
